### PR TITLE
Make sure we always terminate

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
This should be now ready for review, only https://github.com/Dynflow/dynflow/pull/301/commits/a41ac592b0d4fa3caa1c82182a5ef76b5b2c2e9c is really essential

**Comment by iNecas** [comment]
Tested and works well. Thanks @adamruzicka: btw. do we have a BZ and redmine issue to track this problem, so that it's easier to make sure the right versions get the patches?

**Comment by adamruzicka** [comment]
We do have a BZ[1] now.

[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1654975

**Comment by iNecas** [comment]
Note for myself: redmine issue here https://projects.theforeman.org/issues/25593

**Pull request merged**
