### PR TITLE
Use mediumtext instead of text for data columns in mysql

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Do we have an issue for this or is this to avoid potentional issues in the future?

**Comment by iNecas** [comment]
We got a report when trying  https://github.com/theforeman/foreman_ansible/pull/40 - the problem is mysql has different constraints for `:text` than other providers, therefore, we should use `:mediumtext` for all cases where we use `:text` otherwise, to keep the behavior the same

**Comment by adamruzicka** [comment]
I wasn't aware of that report. ACK

**Comment by dLobatog** [comment]
Works for me, no more exceptions on the data column anymore.

**Comment by iNecas** [comment]
released in 0.8.15

**Pull request merged**
