### PR TITLE
Improve finalize documentation

### PR DESCRIPTION
**Pull request by ares**
Please double check that I don't make up something :-)

### CODE REVIEW

**Comment by ares** [comment]
thanks, fixed

**Comment by ares** [comment]
changing doc causing [test] to fail? haha... could someone take a look and merge?

**Comment by iNecas** [comment]
Hey, you just break our tests, HOW DARE YOU! Here is the fix https://github.com/Dynflow/dynflow/pull/183

**Comment by ares** [comment]
please don't call :cop: :-) thanks for quick looking

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
seems like intermittent error on one combination ", [2016-04-27T09:17:57.156192 #3157] ERROR -- /connector-direct-core: No executor available (Dynflow::Error)", [test]

**Comment by ares** [comment]
got the same error on another worker...

**Comment by adamruzicka** [comment]
What's the status here?

**Comment by ares** [comment]
@adamruzicka could you please read and click the green button if you don't find anything wrong?

**Comment by adamruzicka** [comment]
Looks good to me, merging. Thanks @ares!

**Pull request merged**
