### PR TITLE
Add Revert rescue strategy for rolling-back failed tasks

### PR DESCRIPTION
**Pull request by adamruzicka**
~~- [x] tests~~
~~- [x] on-demand rollback of paused (paused - error) and/or failed (stopped - error) tasks?~~
12/06/16
- [ ] tests
- [ ] remove duplicate code
- [ ] remove leftovers from the older implementation
- [ ] reset action output when resuming partially reverted plan

### Tl; dr:
1) Include `::Actions::Dynflow::Revertible` module in your action
2) Implement `#revert_run` and `#revert_plan` methods
3) Call `#revert` on a `paused-error` execution plan

### A bit longer description
Calling `#revert` on an execution plan `E` creates another execution plan `R`, where the actions are planned in reversed order, but with `#revert` method instead of `#plan`, which handles creating the correct rollback plan. For an action with a `#plan` method there should be `#revert_plan` method undoing changes done in the `#plan`. The same goes for `#run` and `#revert_run`.   The `#revert_run`s are always run in a sequence. `#revert_run`s run in run phase, `#revert_plan` run in finalize phase.

When a step from `R` successfully finishes, it changes the state of the corresponding step in `E` to `reverted`

At the end of `R`'s run phase `E`'s state gets changed to `planned`, at the end of `R`'s finalize phase, `E`'s state gets changed to `stopped`

In the `#revert_plan` and `#revert_run` methods one can use `#original_input` and `#original_output` to access the input and output of the action being reverted.

### CODE REVIEW

**Comment by adamruzicka** [comment]
The tests are green

**Comment by adamruzicka** [comment]
Rebased on latest-greatest

**Comment by ohadlevy** [comment]
@adamruzicka it needs a rebase :)

**Comment by adamruzicka** [comment]
@ohadlevy thanks for pointing that out, rebased

**Comment by iNecas** [comment]
Tests are failing after the rebase

**Pull request closed without merging**
