### PR TITLE
Fixes #19146 - handle invalid plans when invalidating worlds

### PR DESCRIPTION
**Pull request by iNecas**
In a corner case, the data can be inconsistent in a way, that prevents
the world to be invalidate properly. Although this is usually a result
of unsafe manipulation with data on database level, we need to try
to resolve the situation to at least keep clean the runtime data properly,
as there is not much more we can do about it.

### CODE REVIEW

**Comment by beav** [comment]
I'm not in dynflow project, but change looks good to me.

**Comment by iNecas** [comment]
@adamruzicka mind to have a look?

**Comment by adamruzicka** [comment]
@iNecas The immediate issue is fixed (the world gets invalidated properly), however the "broken" execution plans are still left behind and accessing dynflow index raises `Dynflow::Errors::DataConsistencyError at /
Could not load steps for execution plan` when it should list some of those plans. It would be nice if we could render the other execution plans on the same page and just mark the broken ones somehow. Is it out of scope of this PR?

**Comment by iNecas** [comment]
Good point, I agree we should hande it there as well, will work on that.

**Comment by iNecas** [comment]
@adamruzicka I've added `ExecutionPlan::InvalidExecutionPlan` object, that is being used when there are issue loading all the data: this can be used still to show the data in console

**Comment by adamruzicka** [comment]
Looks good to me, APT

**Pull request merged**
