### PR TITLE
Honor rescue strategy on abnormal termination

### PR DESCRIPTION
**Pull request by adamruzicka**
- [x] tests

### CODE REVIEW

**Comment by iNecas** [comment]
tests are failing currently, seems like related. Otherwise, the change seems reasonable

**Comment by iNecas** [comment]
Tests seem fine, the rubocop is failing now

**Comment by iNecas** [comment]
ACK so far: it seems we're still waiting for some test coverage?

**Comment by adamruzicka** [comment]
Not anymore

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Comment by iNecas** [comment]
Squashed and merged as 4fd49462a2c8cf8aa

**Pull request merged**
