### PR TITLE
Fixes #15201 - fix the N+1 select issue in execution plan load

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by beav** [comment]
:koala: testing now

**Comment by iNecas** [comment]
Some tests were failling due to order of steps might be different on per databse basis, I've made sure we preserve the order, just to be sure to not cause some unexpected behavior

**Comment by iNecas** [comment]
There is still room for improving the performance of execution plan loading by making the steps loading lazy, but this should be a good start

**Comment by beav** [comment]
I see the following after applying the patch and reloading the CV version page:

```
[pid 10767] 10:45:12.916008 sendto(26, "Q\0\0\0iSELECT * FROM \"dynflow_steps\" WHERE (\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2')\0", 106, MSG_NOSIGNAL, NULL, 0) = 106
[pid 10767] 10:45:13.948663 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.949573 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.950338 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.951033 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.951742 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.952408 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.953335 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.954039 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.954736 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.955932 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.956634 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.957326 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.957998 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.958710 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.959415 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
[pid 10767] 10:45:13.960243 sendto(26, "Q\0\0\0\204SELECT * FROM \"dynflow_actions\" WHERE ((\"execution_plan_uuid\" = '84f92028-8a8e-4156-8a53-e3bdf3b693e2') AND (\"id\" = 1)) LIMIT 1\0", 133, MSG_NOSIGNAL, NULL, 0) = 133
```

There is only one select to `dynflow_steps` now.

**Pull request merged**
