### PR TITLE
Adding jekyll pages to generate Dynflow project page / documentation

### PR DESCRIPTION
**Pull request by pitr-ch**
replaces #137

### CODE REVIEW

**Comment by pitr-ch** [comment]
Changes in #142 pulled here, @ares if you want you can see updates I made a commit following yours.

**Comment by pitr-ch** [comment]
@iNecas ready for review and merge.

**Comment by ares** [comment]
sorry for inline commit comments but the whole PR eats all RAM, since it's huge :-)

**Comment by pitr-ch** [comment]
no problem, thanks for the comments!

**Comment by pitr-ch** [comment]
@iNecas @ares @adamruzicka do we merge, or any pending reviews? @iNecas see README updates.

**Comment by iNecas** [comment]
ACK from me!

**Comment by ares** [comment]
Ack

Odesláno pomocí AquaMail pro Android
http://www.aqua-mail.com


Dne 13. března 2015 13:01:46 Ivan Necas <notifications@github.com> napsal:

**Comment by ares** [comment]
Or maybe just the persistence thing

**Comment by pitr-ch** [comment]
@ares Yeah I'll ping you later so we can find something which works.

**Comment by adamruzicka** [comment]
ACK from me as well

**Pull request merged**
