### PR TITLE
Dead letter handling

### PR DESCRIPTION
**Pull request by adamruzicka**
Spawns one dead letter handler per world, dead letters can be matched by sender, receiver and the message. Matching can be either of `::Dynflow::DeadLetterHandler::Any` (always match), `Proc` which is evaluated with the object or anything else which is checked using `==` against the object.

### CODE REVIEW

**Comment by iNecas** [comment]
I have to test but looks good codewise

**Comment by iNecas** [comment]
Rubocop is not happy though

**Comment by adamruzicka** [comment]
It needed some manual intervention but we're green now

**Comment by iNecas** [comment]
Tests are happy, I am happy :)

**Pull request merged**
