### PR TITLE
Move to GH actions

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Run can be seen here https://github.com/adamruzicka/dynflow/actions/runs/413447326

@ezr-ondrej opinions?

**Comment by adamruzicka** [comment]
```
  1) Failure:
Future Execution::action scheduling#test_0003_delays the action [/home/runner/work/dynflow/dynflow/test/future_execution_test.rb:58]:
Expected |2020-12-10 16:36:25 UTC - 2020-12-10 16:36:25 UTC| (0.933317361) to be <= 0.5.
```
Don't want to look a gift horse in the mouth, but do github actions run on a toaster? :thinking:

**Comment by ezr-ondrej** [comment]
xD can that be some issue of the order of the tests?

**Review by ezr-ondrej — APPROVED** [review]
I say lets merge, let's figure the intermittent error later.

**Pull request merged**
