### PR TITLE
Optimized ordering during serialization

### PR DESCRIPTION
**Pull request by lzap**
According to my measurements, this method is called about 20k times per sync,
it is worth optimizing. Looks like we have most strings and hashes than
everything else, this makes it faster.

```
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     43                            ===  10895
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     39              recursive_to_hash   5175
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     41                          first   5134
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     48                         update   4619
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     24                            ===   1940
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     22                    deserialize   1940
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     32                            ===   1436
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     62                           to_i   1296
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     45                            ===   1288
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    230                          is_a?   1185
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     47                            ===   1037
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     48                         inject    959
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     48                           each    959
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/utils.rb     52               indifferent_hash    944
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/utils.rb     55                            new    944
opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/action.rb    118                         phase?    823
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    280                         to_sym    795
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    280                             []    795
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    280                         update    795
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     25        check_class_key_present    649
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     26                             []    649
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     62                            <=>    648
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     62                         divmod    648
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     62                              +    648
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     25                           to_s    504
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     29                    constantize    499
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/utils.rb     20                    respond_to?    499
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/utils.rb     19                    constantize    499
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     28                           each    480
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     28                         reduce    480
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb     25                             []    477
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    208                          table    386
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    209                          fetch    386
opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/action.rb    143                         output    367
ot/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/persistence_adapters/sequel.rb    340                     with_retry    344
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     58                 string_to_time    342
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     59                           nil?    342
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb      5                             []    337
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb      3                      from_hash    337
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     20                             []    312
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     20                           to_s    312
eforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/serializable.rb     18           check_class_matching    312
opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/action.rb    248                          state    291
opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/action.rb    249                           nil?    291
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb      8                            ===    284
sr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan/output_reference.rb      6                    dereference    284
oreman/tfm/root/usr/share/gems/gems/dynflow-0.8.24/lib/dynflow/execution_plan.rb    132                       include?    270

```

### CODE REVIEW

**Comment by iNecas** [comment]
I have no issue merging this in: just curious if you have any numbers before/after

**Comment by lzap** [comment]
Yeah I did some measurements, but not strong numbers at all. As you mentioned on the IRC, in this context it does not bring much improvements. I was just testing foreman-tracer, nothing in particular.

**Comment by lzap** [comment]
The idea is we have more strings than numbers and more hashes than arrays, that's really it.

**Comment by iNecas** [comment]
Sure, I just don't want people would have too much expectations about this change :) But there is small enhancement and I don't care about the ordering here. Thanks @lzap

**Comment by lzap** [comment]
Yeah I was just sniffing around on Katello 3.4 with my SystemTap script, nothing serious at all.

**Pull request merged**
