### PR TITLE
Access sidekiq config using a non-deprecated way

### PR DESCRIPTION
**Pull request by adamruzicka**
like
```
WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`
```

#431

### CODE REVIEW

**Review by ofedoren — COMMENTED** [review]
Thanks, @adamruzicka, LGTM.

Although, I think I found one more place to change:
 - https://github.com/Dynflow/dynflow/blob/master/lib/dynflow.rb#L28

Should we also update examples then? Such as https://github.com/Dynflow/dynflow/blob/master/examples/remote_executor.rb#L76

**Comment by adamruzicka** [comment]
Ah yes, good catch

**Review by ofedoren — APPROVED** [review]
Thanks, @adamruzicka, :shipit:

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
