### PR TITLE
Improve error messages for missing action

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by iNecas** [comment]
Good to go after rubocop is fixed:

```
lib/dynflow/action/missing.rb:15:167: C: Line is too long. [176/166]
      raise StandardError, "The action class was not found and therefore plan phase failed, this can happen if the action was added/renamed but the executor was not restarted."
                                                                                                                                                                      ^^^^^^^^^^
lib/dynflow/action/missing.rb:19:167: C: Line is too long. [175/166]
      raise StandardError, "The action class was not found and therefore run phase failed, this can happen if the action was added/renamed but the executor was not restarted."
                                                                                                                                                                      ^^^^^^^^^
lib/dynflow/action/missing.rb:23:167: C: Line is too long. [180/166]
      raise StandardError, "The action class was not found and therefore finalize phase failed, this can happen if the action was added/renamed but the executor was not restarted."
                                                                                                                                                                      ^^^^^^^^^^^^^^
```

**Comment by ares** [comment]
> Pending rubocop

:open_mouth: who are you and what did you do with @iNecas? anyway, :cop is happy now

**Comment by adamruzicka** [comment]
Travis is happy as well, merging

**Comment by adamruzicka** [comment]
Thanks @ares

**Pull request merged**
