### PR TITLE
Add run_step_id to DummyAction

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by adamruzicka** [comment]
In general +1, let's see what the tests think

**Comment by ezr-ondrej** [comment]
> In general +1, let's see what the tests think

In theory tests should not touch the method as they do not need it.

**Comment by ezr-ondrej** [comment]
Just mysql, which is broken long term :)

**Comment by adamruzicka** [comment]
Thank you @ezr-ondrej !

**Pull request merged**
