### PR TITLE
[WIP] Add docs for execution plan hooks

### PR DESCRIPTION
**Pull request by adamruzicka**
Docs for https://github.com/Dynflow/dynflow/pull/270

### CODE REVIEW

**Comment by ares** [comment]
LGTM, I hope we'll also have some foreman-tasks wrapper/DSL on top of it and documentation for it too :-)

**Comment by adamruzicka** [comment]
Waiting for https://github.com/Dynflow/dynflow/pull/274, after that goes in I'll switch the base of this PR to master.

**Comment by adamruzicka** [comment]
Rebased and switched base to master

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
